export const SET_DISPLAY_MODE = 'SET_DISPLAY_MODE';
export const POPUP_OPEN = 'POPUP_OPEN';
export const POPUP_CLOSE_ALL = 'POPUP_CLOSE_ALL';
export const SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR';
export const STEP_CONTENT_SHOW_BULLETS = 'STEP_CONTENT_SHOW_BULLETS';
