
export default {
  SET_DISPLAY_MODE: 'SET_DISPLAY_MODE',
  POPUP_OPEN: 'POPUP_OPEN',
  POPUP_CLOSE_ALL: 'POPUP_CLOSE_ALL',
  SET_GLOBAL_ERROR: 'SET_GLOBAL_ERROR',
  STEP_CONTENT_SHOW_BULLETS: 'STEP_CONTENT_SHOW_BULLETS'
};
