
export default {
  DEMOS_SETTINGS_START: 'DEMOS_SETTINGS_START',
  DEMOS_SETTINGS_APPLY: 'DEMOS_SETTINGS_APPLY',
  DEMOS_SETTINGS_CANCEL: 'DEMOS_SETTINGS_CANCEL',
  DEMOS_SETTINGS_INCLUDE_DEMO: 'DEMOS_SETTINGS_INCLUDE_DEMO',
  DEMOS_SETTINGS_EXCLUDE_DEMO: 'DEMOS_SETTINGS_EXCLUDE_DEMO',
  DEMOS_SETTINGS_MOVE_DEMO: 'DEMOS_SETTINGS_MOVE_DEMO'
};
